In [1]:
import pandas as pd

In [2]:
data = [[1, 'Let us Code'], [2, 'More than fifteen chars are here!']]
tweets = pd.DataFrame(data, columns=['tweet_id', 'content']).astype({'tweet_id':'Int64', 'content':'object'})

In [3]:
tweets

   tweet_id                            content
0         1                        Let us Code
1         2  More than fifteen chars are here!

In [14]:
len(str(tweets['content']))

106

In [18]:
tweets[tweets['content'].str.len()>15][['tweet_id']]

   tweet_id
1         2