In [1]:
import pandas as pd

In [2]:
data = [[1, '2015-01-01', 10], [2, '2015-01-02', 25], [3, '2015-01-03', 20], [4, '2015-01-04', 30]]
weather = pd.DataFrame(data, columns=['id', 'recordDate', 'temperature']).astype({'id':'Int64', 'recordDate':'datetime64[ns]', 'temperature':'Int64'})

In [3]:
weather

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

In [17]:
weather['prev_temperature'] = weather.sort_values('recordDate',ascending= True)[['temperature']].shift(1)
weather['prev_date'] = weather.sort_values('recordDate',ascending= True)[['recordDate']].shift(1)
weather['yesterday_date'] = weather['recordDate'] - pd.Timedelta(days=1)
weather[
    (weather.temperature > weather.prev_temperature)
    &
    (weather.prev_date == weather.yesterday_date)
    
][['id']]

   id
1   2
3   4

In [10]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                4 non-null      Int64
 1   recordDate        4 non-null      datetime64[ns]
 2   temperature       4 non-null      Int64
 3   prev_temperature  3 non-null      Int64
dtypes: Int64(3), datetime64[ns](1)
memory usage: 272.0 bytes

In [ ]:
weather['yesterday_date'] = weather['recordDate'] - pd.Timedelta(days=1)

0   2014-12-31
1   2015-01-01
2   2015-01-02
3   2015-01-03
Name: recordDate, dtype: datetime64[ns]