In [1]:
import pandas as pd

In [3]:
data = [[1, 23], [2, 9], [4, 30], [5, 54], [6, 96], [7, 54], [8, 54]]
visits = pd.DataFrame(data, columns=['visit_id', 'customer_id']).astype({'visit_id':'Int64', 'customer_id':'Int64'})
data = [[2, 5, 310], [3, 5, 300], [9, 5, 200], [12, 1, 910], [13, 2, 970]]
transactions = pd.DataFrame(data, columns=['transaction_id', 'visit_id', 'amount']).astype({'transaction_id':'Int64', 'visit_id':'Int64', 'amount':'Int64'})

visits

   visit_id  customer_id
0         1           23
1         2            9
2         4           30
3         5           54
4         6           96
5         7           54
6         8           54

In [5]:
transactions

   transaction_id  visit_id  amount
0               2         5     310
1               3         5     300
2               9         5     200
3              12         1     910
4              13         2     970

In [9]:
visits[~(visits.visit_id.isin(transactions.visit_id.unique()))].groupby('customer_id').agg(
    count_no_trans = ('visit_id','count')
).reset_index()

   customer_id  count_no_trans
0           30               1
1           54               2
2           96               1

In [ ]:
# transactions.visit_id.unique

<bound method Series.unique of 0    5
1    5
2    5
3    1
4    2
Name: visit_id, dtype: Int64>