In [1]:
import pandas as pd

In [2]:
data = [[0, 0, 'start', 0.712], [0, 0, 'end', 1.52], [0, 1, 'start', 3.14], [0, 1, 'end', 4.12], [1, 0, 'start', 0.55], [1, 0, 'end', 1.55], [1, 1, 'start', 0.43], [1, 1, 'end', 1.42], [2, 0, 'start', 4.1], [2, 0, 'end', 4.512], [2, 1, 'start', 2.5], [2, 1, 'end', 5]]
activity = pd.DataFrame(data, columns=['machine_id', 'process_id', 'activity_type', 'timestamp']).astype({'machine_id':'Int64', 'process_id':'Int64', 'activity_type':'object', 'timestamp':'Float64'})
activity

    machine_id  process_id activity_type  timestamp
0            0           0         start      0.712
1            0           0           end       1.52
2            0           1         start       3.14
3            0           1           end       4.12
4            1           0         start       0.55
5            1           0           end       1.55
6            1           1         start       0.43
7            1           1           end       1.42
8            2           0         start        4.1
9            2           0           end      4.512
10           2           1         start        2.5
11           2           1           end        5.0

In [7]:
max_df = activity[activity['activity_type']=='start'].groupby(['machine_id','process_id']).agg( start_timestamp = ('timestamp','max')).reset_index()
min_df = activity[activity['activity_type']=='end'].groupby(['machine_id','process_id']).agg( end_timestamp = ('timestamp','max')).reset_index()

merged = pd.merge(max_df, min_df, on = ['machine_id','process_id'], how = 'inner')
merged['processing'] = merged.end_timestamp - merged.start_timestamp

merged.groupby('machine_id').agg(
    processing_time = ('processing','mean')
).reset_index().round(3)

   machine_id  processing_time
0           0            0.894
1           1            0.995
2           2            1.456